#!/usr/bin/env python3
"""Render the daily RADAR Stream A digest as an email-safe HTML file.

Reads candidates.json (produced by radar_process.py) and writes a static HTML digest —
inline styles only, no JS (email clients strip scripts). Used by the daily-data workflow to
email the digest via SMTP.

    python radar/scripts/render_email.py --candidates data/radar/candidates.json \
        --date 2026-07-04 --out /tmp/radar_email.html

Exit codes: 0 = wrote digest; 2 = candidates.json is missing or not for --date (skip send).
"""
import argparse, json, os, html, sys

TIER = {
    "TOP":  ("🔴 TOP — 官方門戶更新", "#c62828"),
    "HIGH": ("🟠 HIGH", "#e8870c"),
    "MED":  ("🟡 MED", "#b59a00"),
}


def esc(s):
    return html.escape(s or "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", required=True)
    ap.add_argument("--date", required=True, help="expected run date YYYY-MM-DD (Taipei)")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    if not os.path.exists(a.candidates):
        print(f"[email] {a.candidates} missing — skipping send", file=sys.stderr)
        sys.exit(2)
    c = json.load(open(a.candidates, encoding="utf-8"))
    if c.get("date") != a.date:
        print(f"[email] candidates date {c.get('date')} != {a.date} (RADAR likely failed) — skipping send",
              file=sys.stderr)
        sys.exit(2)

    stream_a = c.get("stream_a", [])
    stream_b = c.get("stream_b", [])
    st = c.get("stats", {})

    parts = [
        '<div style="font-family:-apple-system,Segoe UI,Roboto,\'Noto Sans TC\',sans-serif;'
        'max-width:720px;margin:0 auto;color:#1a1a1a;line-height:1.5">',
        f'<h1 style="font-size:20px;margin:0 0 2px">國際新聞蒐集 — 每日雷達 (Stream A · CBAM core)</h1>',
        f'<div style="color:#666;font-size:13px;margin-bottom:16px">{esc(a.date)} · '
        f'{len(stream_a)} candidates · {len(stream_b)} reference (Stream B) · '
        f'{st.get("dropped_stale",0)} stale / {st.get("dropped_evergreen",0)} evergreen filtered</div>',
    ]

    if not stream_a:
        parts.append('<p style="color:#666">No CBAM-core candidates today.</p>')

    for tier in ("TOP", "HIGH", "MED"):
        group = [i for i in stream_a if i.get("tier") == tier]
        if not group:
            continue
        label, color = TIER[tier]
        parts.append(f'<h2 style="font-size:15px;margin:18px 0 8px;color:{color}">'
                     f'{esc(label)} ({len(group)})</h2>')
        for i in group:
            summ = (i.get("summary") or "")[:220]
            parts.append(
                '<div style="margin:0 0 12px;padding-left:10px;border-left:3px solid {c}">'
                '<a href="{u}" style="font-size:14px;font-weight:600;color:#0b5;text-decoration:none">{t}</a>'
                '<div style="color:#888;font-size:12px;margin:2px 0">{src} · {pub} · {top}</div>'
                '{s}</div>'.format(
                    c=color, u=esc(i.get("url")), t=esc(i.get("title")),
                    src=esc(i.get("source")), pub=esc(i.get("published")), top=esc(i.get("topic")),
                    s=f'<div style="font-size:13px;color:#333">{esc(summ)}</div>' if summ else ""))

    parts.append(
        '<hr style="border:0;border-top:1px solid #eee;margin:20px 0">'
        '<div style="color:#999;font-size:11px">Auto-generated by cbam-monitor RADAR. '
        'Stream B (VCM/broader) is collected for reference and not shown here.</div></div>')

    with open(a.out, "w", encoding="utf-8") as f:
        f.write("".join(parts))
    print(f"[email] wrote {a.out} (Stream A {len(stream_a)})")


if __name__ == "__main__":
    main()
