#!/usr/bin/env python3
"""Render a RADAR digest as an email-safe HTML file (inline styles only, no JS).

Reads candidates.json (produced by radar_process.py) and writes a static HTML digest for
either stream:
  --stream a  (default) : Stream A — CBAM core, grouped by tier TOP/HIGH/MED (daily email)
  --stream b            : Stream B — VCM / 廣義碳市場 reference, grouped by topic (weekly email)

    python radar/scripts/render_email.py --candidates data/radar/candidates.json \
        --date 2026-07-04 --out /tmp/radar_email.html [--stream a|b]

Exit codes: 0 = wrote digest; 2 = candidates.json missing or not for --date (skip send).

Machine-readable payload: a numbered item list is embedded as an HTML comment
(<!--RADAR_ITEMS_JSON:[...]-->) right before the closing tag. It never renders visually.
carbon-news-collector's RADAR mode reads it back with parse_digest_email.py instead of
re-parsing the visible markup, which Gmail/forwarding can reformat.
"""
import argparse, json, os, html, sys
from collections import OrderedDict

TIER = {
    "TOP":  ("🔴 TOP — 官方門戶更新", "#c62828"),
    "HIGH": ("🟠 HIGH", "#e8870c"),
    "MED":  ("🟡 MED", "#b59a00"),
}
WRAP_OPEN = ('<div style="font-family:-apple-system,Segoe UI,Roboto,\'Noto Sans TC\',sans-serif;'
             'max-width:720px;margin:0 auto;color:#1a1a1a;line-height:1.5">')


def esc(s):
    return html.escape(s or "")


def item_block(i, color):
    summ = (i.get("summary") or "")[:220]
    return (
        '<div style="margin:0 0 12px;padding-left:10px;border-left:3px solid {c}">'
        '<a href="{u}" style="font-size:14px;font-weight:600;color:#0b5;text-decoration:none">{t}</a>'
        '<div style="color:#888;font-size:12px;margin:2px 0">{src} · {pub} · {top}</div>'
        '{s}</div>'.format(
            c=color, u=esc(i.get("url")), t=esc(i.get("title")),
            src=esc(i.get("source")), pub=esc(i.get("published")), top=esc(i.get("topic")),
            s=f'<div style="font-size:13px;color:#333">{esc(summ)}</div>' if summ else ""))


def footer_with_payload(payload):
    blob = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return (
        '<hr style="border:0;border-top:1px solid #eee;margin:20px 0">'
        '<div style="color:#999;font-size:11px">Auto-generated by carbon-news RADAR.</div>'
        f'<!--RADAR_ITEMS_JSON:{blob}-->'
        '</div>')


def render_a(c, date):
    a = c.get("stream_a", [])
    st = c.get("stats", {})
    out = [WRAP_OPEN,
           '<h1 style="font-size:20px;margin:0 0 2px">國際新聞蒐集 — 每日雷達 (Stream A · CBAM core)</h1>',
           f'<div style="color:#666;font-size:13px;margin-bottom:16px">{esc(date)} · {len(a)} candidates · '
           f'{st.get("dropped_stale",0)} stale / {st.get("dropped_evergreen",0)} evergreen filtered</div>']
    if not a:
        out.append('<p style="color:#666">No CBAM-core candidates today.</p>')
    payload = []
    n = 0
    for tier in ("TOP", "HIGH", "MED"):
        group = [i for i in a if i.get("tier") == tier]
        if not group:
            continue
        label, color = TIER[tier]
        out.append(f'<h2 style="font-size:15px;margin:18px 0 8px;color:{color}">{esc(label)} ({len(group)})</h2>')
        out += [item_block(i, color) for i in group]
        for i in group:
            n += 1
            payload.append({"n": n, "stream": "a", "tier": tier, "topic": i.get("topic", ""),
                             "title": i.get("title", ""), "url": i.get("url", ""),
                             "source": i.get("source", ""), "published": i.get("published", "")})
    out.append(footer_with_payload(payload))
    return "".join(out), len(a)


def render_b(c, date):
    b = c.get("stream_b", [])
    out = [WRAP_OPEN,
           '<h1 style="font-size:20px;margin:0 0 2px">碳權市場週報 — VCM / 廣義碳市場參考</h1>',
           f'<div style="color:#666;font-size:13px;margin-bottom:16px">{esc(date)} · past 7 days · '
           f'{len(b)} items · 研究用，不進 CBAM 週報</div>']
    if not b:
        out.append('<p style="color:#666">No VCM / broader-market items this week.</p>')
    # group by topic, preserving first-seen order; items newest-first within a topic
    by_topic = OrderedDict()
    for i in sorted(b, key=lambda x: x.get("published", ""), reverse=True):
        by_topic.setdefault(i.get("topic") or "其他 Other", []).append(i)
    payload = []
    n = 0
    for topic, group in by_topic.items():
        out.append(f'<h2 style="font-size:15px;margin:18px 0 8px;color:#1d9e75">{esc(topic)} ({len(group)})</h2>')
        out += [item_block(i, "#1d9e75") for i in group]
        for i in group:
            n += 1
            payload.append({"n": n, "stream": "b", "tier": "", "topic": topic,
                             "title": i.get("title", ""), "url": i.get("url", ""),
                             "source": i.get("source", ""), "published": i.get("published", "")})
    out.append(footer_with_payload(payload))
    return "".join(out), len(b)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", required=True)
    ap.add_argument("--date", required=True, help="expected run date YYYY-MM-DD (Taipei)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--stream", choices=["a", "b"], default="a")
    a = ap.parse_args()

    if not os.path.exists(a.candidates):
        print(f"[email] {a.candidates} missing — skipping send", file=sys.stderr)
        sys.exit(2)
    c = json.load(open(a.candidates, encoding="utf-8"))
    if c.get("date") != a.date:
        print(f"[email] candidates date {c.get('date')} != {a.date} (RADAR likely failed) — skipping send",
              file=sys.stderr)
        sys.exit(2)

    html_out, n = render_a(c, a.date) if a.stream == "a" else render_b(c, a.date)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"[email] wrote {a.out} (stream {a.stream.upper()}, {n} items)")


if __name__ == "__main__":
    main()
