#!/usr/bin/env python3
"""Render the weekly carbon-news digest as an email-safe HTML file (inline styles only, no JS).

Reads candidates.json (produced by radar_process.py) and writes a single static HTML digest
grouped by topic bucket:

    python scripts/render_email.py --candidates /tmp/radar/candidates.json \
        --date 2026-07-21 --out /tmp/radar_email.html

Restructured July 2026: the daily/weekly split and the TOP/HIGH/MED tiers are gone, so there
is one renderer and no --stream argument. The hidden RADAR_ITEMS_JSON payload was removed at
the same time — it existed only for the retired Cowork skill's pick-list parsing.

Exit codes: 0 = wrote digest; 2 = candidates.json missing or not for --date (skip send).
"""
import argparse, json, os, html, sys
from collections import OrderedDict

# Bucket order — kept in sync with TOPIC_ORDER in scripts/fetch_feeds.py.
TOPIC_ORDER = [
    "Compliance Carbon Markets 強制性碳市場",
    "Taiwan 台灣碳市場與綠色金融",
    "Voluntary Carbon Market (VCM) 自願性碳市場",
    "Article 6 & CORSIA 第六條與航空",
    "Carbon Removal & Nature 碳移除與自然碳匯",
    "Industry & Trade Response 產業與貿易回應",
    "Analysis & Research 分析與研究",
    "Other 其他",
]
ACCENT = "#1d9e75"
WRAP_OPEN = ('<div style="font-family:-apple-system,Segoe UI,Roboto,\'Noto Sans TC\',sans-serif;'
             'max-width:720px;margin:0 auto;color:#1a1a1a;line-height:1.5">')


def esc(s):
    return html.escape(s or "")


def item_block(i):
    summ = (i.get("summary") or "")[:220]
    return (
        '<div style="margin:0 0 12px;padding-left:10px;border-left:3px solid {c}">'
        '<a href="{u}" style="font-size:14px;font-weight:600;color:#0b5;text-decoration:none">{t}</a>'
        '<div style="color:#888;font-size:12px;margin:2px 0">{src} · {pub}</div>'
        '{s}</div>'.format(
            c=ACCENT, u=esc(i.get("url")), t=esc(i.get("title")),
            src=esc(i.get("source")), pub=esc(i.get("published")),
            s=f'<div style="font-size:13px;color:#333">{esc(summ)}</div>' if summ else ""))


def footer():
    return (
        '<hr style="border:0;border-top:1px solid #eee;margin:20px 0">'
        '<div style="color:#999;font-size:11px">Auto-generated by carbon-news.</div>'
        '</div>')


def render(c, date):
    items = c.get("items", [])
    st = c.get("stats", {})
    out = [WRAP_OPEN,
           '<h1 style="font-size:20px;margin:0 0 2px">Carbon News 碳市場每週彙整</h1>',
           f'<div style="color:#666;font-size:13px;margin-bottom:16px">{esc(date)} · past 7 days · '
           f'{len(items)} items · {st.get("dropped_stale",0)} stale / '
           f'{st.get("dropped_evergreen",0)} evergreen filtered</div>']
    if not items:
        out.append('<p style="color:#666">No items this week.</p>')

    # Group by bucket, following TOPIC_ORDER; radar_process already ordered the list.
    by_topic = OrderedDict((t, []) for t in TOPIC_ORDER)
    for i in items:
        by_topic.setdefault(i.get("topic") or "Other 其他", []).append(i)

    for topic, group in by_topic.items():
        if not group:
            continue
        out.append(f'<h2 style="font-size:15px;margin:18px 0 8px;color:{ACCENT}">'
                   f'{esc(topic)} ({len(group)})</h2>')
        out += [item_block(i) for i in group]
    out.append(footer())
    return "".join(out), len(items)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", required=True)
    ap.add_argument("--date", required=True, help="expected run date YYYY-MM-DD (Taipei)")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    if not os.path.exists(a.candidates):
        print(f"[email] {a.candidates} missing — skipping send", file=sys.stderr)
        sys.exit(2)
    c = json.load(open(a.candidates, encoding="utf-8"))
    if c.get("date") != a.date:
        print(f"[email] candidates date {c.get('date')} != {a.date} (RADAR likely failed) — skipping send",
              file=sys.stderr)
        sys.exit(2)

    html_out, n = render(c, a.date)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(html_out)
    print(f"[email] wrote {a.out} ({n} items)")


if __name__ == "__main__":
    main()
